# Generated by Django 4.2.2 on 2023-06-26 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_alter_dance_course_instance_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dance_course_instance',
            options={'ordering': ['start_date'], 'permissions': (('can_set_run_status', 'set course as runnin or other'),)},
        ),
        migrations.AlterField(
            model_name='dance_course_instance',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Put in the Footloose members that attend this course', to=settings.AUTH_USER_MODEL),
        ),
    ]
