# Generated by Django 4.2.2 on 2023-06-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_dance_course_instance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dance_course_instance',
            options={'ordering': ['start_date'], 'permissions': (('acces_to_participants', 'access the attending participants'),)},
        ),
    ]
